
# ansible -m copy -a "src=../adhoc/master.gitconfig dest=~/.gitconfig" localhost

- name: Ensure ~./gitconfig copied from master.gitconfig
  gather_facts: false 
  hosts: localhost
  tasks:
  - copy: src="~/myGit/master.gitconfig" dest="~/.gitconfig"


